region                   = "us-central1"
gke_cluster_name         = "dev-fest-demo"
sync_repo   = "https://github.com/terraform-google-modules/terraform-google-kubernetes-engine.git"
sync_branch = "master"
policy_dir  = "examples/acm-terraform-blog-part1/config-root"