region           = "us-central1-b"
gke_cluster_name = "dev-fest-cdmx-2022-dev"
sync_repo        = "https://github.com/yolitals/gke-with-anthos.git"
sync_branch      = "master"
policy_dir       = "anthos/policies/config-root"